# Shared UAT output + evidence reporting. Sourced by every test/uat_*.sh:
#
#     . "${HERE}/lib/report.sh"
#     report_begin <order> <slug> "<title>" "<what passing PROVES about the platform>"
#     ... say / ok / bad / info ...
#     report_finish        # then: exit "${FAILED}"
#
# Each ok/bad is one ASSERTION, and its message is written to carry the EVIDENCE inline — a
# live user name, a session id, a row count — because "PASS" alone proves that a check ran,
# not that the platform is in the claimed state. Anyone reading the report should be able to
# dispute an assertion from what is printed next to it.
#
# Every run rewrites its own fragment in test/results/ and regenerates UAT-REPORT.md from all
# fragments, ordered by the <order> prefix — which follows the platform's own dependency
# order, so the report reads as the end state being built up: network policy, then brokered
# access, then secrets, then the evidence pipeline, then analysis on top of all of it.

REPORT_DIR="${PLATFORM}/test/results"
REPORT_FRAG=""
REPORT_TITLE=""
_R_PASS=0; _R_FAIL=0
FAILED=0

say()  { printf '\n\033[1;36m== %s\033[0m\n' "$*"; _r_section "$*"; }
ok()   { printf '  \033[1;32mPASS\033[0m %s\n' "$*"; _r_line PASS "$*"; }
bad()  { printf '  \033[1;31mFAIL\033[0m %s\n' "$*"; FAILED=1; _r_line FAIL "$*"; }
info() { printf '  \033[0;37m%s\033[0m\n' "$*"; _r_line note "$*"; }

_r_esc() { printf '%s' "$1" | sed 's/|/\\|/g'; }

_r_section() {
    [[ -n "${REPORT_FRAG}" ]] || return 0
    {   printf '\n**%s**\n\n' "$(_r_esc "$1")"
        printf '| Result | Assertion — with evidence |\n|---|---|\n'
    } >> "${REPORT_FRAG}"
}

_r_line() {
    [[ -n "${REPORT_FRAG}" ]] || return 0
    local mark
    case "$1" in
        PASS) mark="✅ PASS" ;;
        FAIL) mark="❌ **FAIL**" ;;
        *)    mark="·" ;;
    esac
    printf '| %s | %s |\n' "${mark}" "$(_r_esc "$2")" >> "${REPORT_FRAG}"
}

report_begin() {  # <order> <slug> <title> <claim>
    local order="$1" slug="$2"; REPORT_TITLE="$3"; local claim="$4"
    mkdir -p "${REPORT_DIR}"
    REPORT_FRAG="${REPORT_DIR}/${order}-${slug}.md"
    printf '\033[1;33m!! These tests act on the RUNNING deployment.\033[0m\n'
    printf '\033[0;37m   Intended use: bring the stack up, run these to VALIDATE it, then rebuild.\n'
    printf '     deploy.sh enclave  ->  test/uat_*.sh  ->  deploy.sh down enclave && deploy.sh enclave\n'
    printf '   They rotate live credentials, register services and open real sessions, so the\n'
    printf '   stack they leave behind is a tested one, not a clean one. Reports under\n'
    printf '   test/results/ record live user names and identifiers — treat them as sensitive.\033[0m\n'
    {   printf '## %s\n\n' "${REPORT_TITLE}"
        printf '*What passing proves:* %s\n\n' "${claim}"
        printf -- '- Run: `%s` — %s\n' "uat_${slug}.sh" "$(date -u '+%Y-%m-%d %H:%M:%SZ')"
    } > "${REPORT_FRAG}"
}

report_finish() {
    [[ -n "${REPORT_FRAG}" ]] || return 0
    _R_PASS="$(grep -c '^| ✅' "${REPORT_FRAG}" || true)"
    _R_FAIL="$(grep -c '^| ❌' "${REPORT_FRAG}" || true)"
    local verdict="PROVEN"
    [[ "${FAILED}" != "0" ]] && verdict="NOT PROVEN"
    printf '\n**Verdict: %s** — %s assertions passed, %s failed.\n' \
        "${verdict}" "${_R_PASS}" "${_R_FAIL}" >> "${REPORT_FRAG}"

    # Regenerate the collective report from every fragment present. Order is the filename's
    # numeric prefix, so the document builds the platform up the way the deployment does.
    local out="${REPORT_DIR}/UAT-REPORT.md" f
    {   printf '# IR Platform — UAT results\n\n'
        printf 'Generated by `test/uat_*.sh` against the RUNNING deployment; each run rewrites its own section.\n'
        printf 'Last update: %s.\n\n' "$(date -u '+%Y-%m-%d %H:%M:%SZ')"
        printf '> **These tests act on the running deployment.** Bring the stack up, run them to\n'
        printf '> validate it, then rebuild:\n'
        printf '>\n'
        printf '> ```\n'
        printf '> deploy.sh enclave\n'
        printf '> test/uat_consul.sh   # and the rest\n'
        printf '> deploy.sh down enclave && deploy.sh enclave\n'
        printf '> ```\n'
        printf '>\n'
        printf '> They rotate live database credentials, register services into the mesh and open\n'
        printf '> real brokered sessions — so the stack they leave behind is a tested one, not a\n'
        printf '> clean one.\n'
        printf '>\n'
        printf '> The evidence below is deliberately specific — dynamic user names, session and\n'
        printf '> worker identifiers, row counts — because "PASS" alone proves only that a check\n'
        printf '> ran. That makes these files sensitive; they are not a public artifact.\n\n'
        printf '## Summary\n\n| # | UAT | Verdict | Pass | Fail |\n|---|---|---|---|---|\n'
        for f in "${REPORT_DIR}"/[0-9]*-*.md; do
            [[ -f "$f" ]] || continue
            local t v p x n
            n="$(basename "$f")"; n="${n%%-*}"
            t="$(sed -n 's/^## //p' "$f" | head -1)"
            v="$(sed -n 's/^\*\*Verdict: \([A-Z ]*\)\*\*.*/\1/p' "$f" | tail -1)"
            p="$(grep -c '^| ✅' "$f" || true)"; x="$(grep -c '^| ❌' "$f" || true)"
            [[ "${v}" == "PROVEN" ]] && v="✅ PROVEN" || v="❌ ${v:-INCOMPLETE}"
            printf '| %s | %s | %s | %s | %s |\n' "${n}" "${t}" "${v}" "${p}" "${x}"
        done
        printf '\n---\n'
        for f in "${REPORT_DIR}"/[0-9]*-*.md; do
            [[ -f "$f" ]] || continue
            printf '\n'; cat "$f"; printf '\n---\n'
        done
    } > "${out}"
    printf '\n  \033[0;37mreport: %s (section) -> %s\033[0m\n' \
        "$(basename "${REPORT_FRAG}")" "${out}"
}
