# Generated by Django 6.0.7 on 2026-07-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_id', models.IntegerField(db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('patient_zero', models.CharField(blank=True, max_length=255)),
                ('initial_vector', models.CharField(blank=True, max_length=255)),
                ('first_activity', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('host_count', models.IntegerField(default=0)),
                ('confidence', models.CharField(default='Medium', max_length=16)),
                ('linking_evidence', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-host_count'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_id', models.IntegerField(db_index=True)),
                ('investigation_name', models.CharField(blank=True, max_length=255)),
                ('algorithm_version', models.CharField(default='1.0', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_hostname', models.CharField(db_index=True, max_length=255)),
                ('dst_hostname', models.CharField(db_index=True, max_length=255)),
                ('technique', models.CharField(blank=True, max_length=64)),
                ('protocol', models.CharField(blank=True, max_length=32)),
                ('account', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('source_finding_id', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='correlation.campaign')),
            ],
            options={
                'ordering': ['observed_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(db_index=True)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('patient_zero', 'patient_zero'), ('pivot', 'pivot'), ('affected', 'affected')], default='affected', max_length=16)),
                ('first_activity', models.DateTimeField(blank=True, null=True)),
                ('entry_technique', models.CharField(blank=True, max_length=64)),
                ('entry_account', models.CharField(blank=True, max_length=255)),
                ('tp_count', models.IntegerField(default=0)),
                ('techniques', models.JSONField(blank=True, default=list)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='correlation.campaign')),
            ],
            options={
                'ordering': ['first_activity', 'hostname'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='correlation.correlationrun'),
        ),
        migrations.CreateModel(
            name='SharedIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('value', models.CharField(db_index=True, max_length=1024)),
                ('host_count', models.IntegerField(default=0)),
                ('hostnames', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='correlation.campaign')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='correlation.correlationrun')),
            ],
            options={
                'ordering': ['-host_count', 'kind', 'value'],
                'indexes': [models.Index(fields=['kind', 'value'], name='correlation_kind_40a250_idx')],
            },
        ),
    ]
