# Generated by Django 6.0.7 on 2026-08-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0007_convention_examples'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attributioncandidate',
            new_name='correlation_campaig_97af64_idx',
            old_name='corr_attr_camp_score_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorevent',
            new_name='correlation_run_id_ea7a3c_idx',
            old_name='corr_bevent_run_host_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviornode',
            new_name='correlation_run_id_77ab61_idx',
            old_name='corr_bnode_run_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignfingerprint',
            new_name='correlation_investi_3d299f_idx',
            old_name='corr_fp_inv_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignsimilarity',
            new_name='correlation_campaig_ed82ce_idx',
            old_name='corr_sim_camp_score_idx',
        ),
        migrations.RenameIndex(
            model_name='hostlink',
            new_name='correlation_run_id_0f92ba_idx',
            old_name='corr_hlink_run_linked_idx',
        ),
    ]
