#!/usr/bin/env bash
# CA, agent certificate, gossip key and ACL tokens for Consul's control plane.
#
#   ./gen-consul-secrets.sh [--force]
#
# Three separate protections, often confused for one:
#   encrypt        symmetric key for the gossip pool
#   tls{}          mutual TLS on the CONTROL plane (RPC/HTTPS/gRPC)
#   Connect mTLS   between SIDECARS, issued by Consul's own CA — not this script
#
# Secrets are declared here, not discovered later. `consul acl bootstrap` returns its token once
# and losing it means an ACL reset; generating them first also means every token file exists
# before a sidecar bind-mounts it, and a missing mount silently becomes an empty directory.
#
# Regenerating invalidates every agent at once, so it takes --force.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEC="${IR_CONSUL_SECRET_DIR:-${HERE}/secrets}"
DC="${IR_CONSUL_DATACENTER:-dc1}"

MESH_SERVICES=(ir-postgres ir-minio ir-redis ir-backend ir-worker ir-puller ir-vault ir-keycloak ir-frontend ir-oauth2-proxy ir-log-shipper)

mkdir -p "${SEC}/tokens"
chmod 700 "${SEC}" "${SEC}/tokens"

# Consul requires every ACL secret to be a UUID and refuses anything else at start-up.
uuid() {
    if [[ -r /proc/sys/kernel/random/uuid ]]; then cat /proc/sys/kernel/random/uuid
    else python3 -c 'import uuid; print(uuid.uuid4())'
    fi
}

# One token file per mesh service, plus the agent's, the management token, and the read-only
# one the health page reads the catalog with.
token_names() { printf '%s\n' agent management ui-readonly "${MESH_SERVICES[@]}"; }

# BACKFILL BEFORE THE EARLY EXIT. A deployment that predates a newly added token has all the
# other material, so an early exit would skip the new one — and compose, mounting a path that
# does not exist, creates a DIRECTORY there.
backfill() {
    local n f made=0
    while read -r n; do
        f="${SEC}/tokens/${n}.token"
        [[ -d "${f}" ]] && rmdir "${f}" 2>/dev/null
        [[ -s "${f}" ]] && continue
        printf '%s' "$(uuid)" > "${f}"; chmod 644 "${f}"; made=$((made+1))
    done < <(token_names)
    (( made > 0 )) && echo "[consul-secrets] generated ${made} missing token file(s)"
    return 0
}

if [[ -f "${SEC}/consul-agent.pem" && "${1:-}" != "--force" ]]; then
    backfill
    echo "[consul-secrets] material already exists (use --force to regenerate)"
    exit 0
fi

# verify_server_hostname requires this exact name, which is what stops a compromised client
# agent holding a valid certificate from impersonating a server.
SRV_CN="server.${DC}.consul"

openssl req -x509 -newkey rsa:4096 -nodes -days 1825 \
    -keyout "${SEC}/consul-ca-key.pem" -out "${SEC}/consul-ca.pem" \
    -subj "/CN=IR Platform Consul CA" \
    -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null

openssl req -new -newkey rsa:4096 -nodes \
    -keyout "${SEC}/consul-agent-key.pem" -out "${SEC}/consul-agent.csr" \
    -subj "/CN=${SRV_CN}" 2>/dev/null

# Both usages: an agent is a server to its peers and a client to them in turn.
cat > "${SEC}/agent.ext" <<EXT
subjectAltName = DNS:${SRV_CN},DNS:consul,DNS:localhost,IP:127.0.0.1
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth,clientAuth
EXT

openssl x509 -req -in "${SEC}/consul-agent.csr" -days 825 \
    -CA "${SEC}/consul-ca.pem" -CAkey "${SEC}/consul-ca-key.pem" -CAcreateserial \
    -extfile "${SEC}/agent.ext" -out "${SEC}/consul-agent.pem" 2>/dev/null
rm -f "${SEC}/consul-agent.csr" "${SEC}/agent.ext"

# Gossip key: 32 bytes base64, Consul rejects anything else.
GOSSIP="$(openssl rand -base64 32)"

MGMT="$(uuid)"
printf '%s' "$(uuid)" > "${SEC}/tokens/agent.token"
# The health page's credential: reads the catalog and the intentions, writes nothing. Separate
# from ir-backend's own service token, which is scoped to registering itself.
printf '%s' "$(uuid)" > "${SEC}/tokens/ui-readonly.token"
for svc in "${MESH_SERVICES[@]}"; do
    printf '%s' "$(uuid)" > "${SEC}/tokens/${svc}.token"
done

# Kept out of server.hcl because that file is in version control. -config-dir merges both.
cat > "${SEC}/agent-secrets.hcl" <<HCL
# GENERATED by gen-consul-secrets.sh — secrets, not in version control.
encrypt = "${GOSSIP}"

acl {
  tokens {
    initial_management = "${MGMT}"
    agent              = "$(cat "${SEC}/tokens/agent.token")"
  }
}
HCL

printf '%s' "${MGMT}" > "${SEC}/tokens/management.token"

# The 0700 directories are what protect these on the host. The files themselves are readable
# because Consul's entrypoint drops to uid 100 and Envoy runs as its own user, so a 0600 file
# owned by the deploying user is unreadable inside the container it is mounted into.
chmod 600 "${SEC}/consul-ca-key.pem"
chmod 644 "${SEC}"/consul-agent-key.pem "${SEC}"/agent-secrets.hcl \
          "${SEC}"/consul-ca.pem "${SEC}"/consul-agent.pem "${SEC}"/tokens/*.token

echo "[consul-secrets] CA + agent cert (CN=${SRV_CN}), gossip key, management token"
echo "[consul-secrets] service tokens: ${MESH_SERVICES[*]} (+ agent) in ${SEC}/tokens"
