# Consul — the enclave's service mesh control plane.
#
# WHAT ENFORCES THESE. Nothing here, on its own. An intention is applied by the Envoy sidecar in
# front of each service, and only reaches traffic because Postgres and MinIO bind LOOPBACK — see
# IR_DB_LISTEN / IR_MINIO_LISTEN — so the sidecar is the only listener the enclave network can
# reach. Without that binding these rules are a document, which is exactly what they were before
# the mesh was wired: Consul answered "denied" while the connection succeeded.

datacenter  = "dc1"
server      = true
node_name   = "ir-consul"
data_dir    = "/consul/data"
log_level   = "INFO"
client_addr = "0.0.0.0"

# One server. The enclave is a single failure domain already — losing it loses the evidence
# store — so mesh quorum across three nodes would add operational weight without adding
# survivability. Raise this with the node count if the enclave ever spans hosts.
bootstrap_expect = 1

ui_config { enabled = true }
connect   { enabled = true }

# Gossip key, management token and agent token are secrets and live in agent-secrets.hcl,
# generated by gen-consul-secrets.sh. -config-dir merges both.

# Without default-deny, any service reaching the API can read the intentions below and delete
# them — the policy would be writable by the things it governs. Sidecars carry service-identity
# tokens (consul-acl-bootstrap.sh); the anonymous token carries no policy.
acl {
  enabled        = true
  default_policy = "deny"
  # Honor cached policy if the leader is unreachable. "deny" would turn a control-plane blip
  # into a full enclave outage.
  down_policy = "extend-cache"
  # Agent token survives a restart instead of waiting for the next bootstrap run.
  enable_token_persistence = true
}

# Control-plane TLS. Separate from Connect mTLS between sidecars, which Consul issues itself.
tls {
  defaults {
    ca_file   = "/consul/tls/consul-ca.pem"
    cert_file = "/consul/tls/consul-agent.pem"
    key_file  = "/consul/tls/consul-agent-key.pem"

    verify_outgoing = true

    # verify_incoming demands a CLIENT certificate from every caller. On HTTPS/gRPC the callers
    # are sidecars and operators authenticating with ACL tokens, so it stays false here and true
    # on internal_rpc, where a certificate IS the credential.
    verify_incoming = false
  }

  internal_rpc {
    verify_incoming = true
    # Peer certificate must be named server.<datacenter>.consul — stops a compromised client
    # agent with a valid certificate from impersonating a server.
    verify_server_hostname = true
  }
}

# Server half of automatic certificate distribution, for client agents on other hosts.
auto_encrypt { allow_tls = true }

ports {
  # Cleartext HTTP and gRPC are off, not merely unused: left listening they are a second,
  # unauthenticated path to the same API.
  http     = -1
  https    = 8501
  grpc     = -1
  grpc_tls = 8503
  dns      = 8600
}

# NO config_entries block, deliberately. `bootstrap` entries apply only when the entry does not
# already exist, so an intention edited here never reaches a cluster whose data volume predates
# the edit — the policy on disk and the policy in force silently diverge, which is how Vault was
# denied a database it was plainly allowed. The entries live in config-entries/*.hcl and are
# WRITTEN on every deployment by consul-acl-bootstrap.sh; `consul config write` is idempotent
# and converges the live state to the files.
