# Generated by Django 6.0.7 on 2026-07-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryanalysisrun',
            name='investigation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProcessVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField(db_index=True)),
                ('process', models.CharField(blank=True, max_length=255)),
                ('engine_label', models.CharField(max_length=32)),
                ('verdict', models.CharField(choices=[('False Positive', 'False Positive'), ('Likely False Positive', 'Likely False Positive'), ('Indeterminate', 'Indeterminate'), ('Likely True Positive', 'Likely True Positive'), ('True Positive', 'True Positive')], db_index=True, max_length=32)),
                ('confidence', models.CharField(blank=True, max_length=32)),
                ('positive_weight', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('mitre', models.JSONField(blank=True, default=list)),
                ('positive_dims', models.JSONField(blank=True, default=list)),
                ('prior_adjudication', models.CharField(blank=True, max_length=64)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_verdicts', to='cases.memoryanalysisrun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_verdicts', to='cases.collectionrun')),
            ],
            options={
                'ordering': ['-positive_weight', 'pid'],
                'indexes': [models.Index(fields=['run', 'verdict'], name='cases_proce_run_id_04a726_idx')],
            },
        ),
    ]
