# Generated by Django 6.0.7 on 2026-07-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_memoryanalysisrun_investigation_processverdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingreclassification',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclassifications', to='cases.investigation'),
        ),
        migrations.AddField(
            model_name='note',
            name='author_role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='note',
            name='confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16),
        ),
        migrations.AddField(
            model_name='note',
            name='findings',
            field=models.ManyToManyField(blank=True, related_name='case_notes', to='cases.finding'),
        ),
        migrations.AddField(
            model_name='note',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to='cases.host'),
        ),
        migrations.AddField(
            model_name='note',
            name='kind',
            field=models.CharField(choices=[('observation', 'Observation'), ('analysis', 'Analysis'), ('decision', 'Decision'), ('action', 'Action taken'), ('containment', 'Containment'), ('eradication', 'Eradication'), ('handoff', 'Handoff'), ('request', 'Request')], db_index=True, default='observation', max_length=16),
        ),
        migrations.AddField(
            model_name='note',
            name='mitre',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='note',
            name='occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='retracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='retracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='retracted_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='note',
            name='retraction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='regionanalysis',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_analyses', to='cases.investigation'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['investigation', 'kind'], name='cases_note_investi_fc1355_idx'),
        ),
    ]
