# Generated by Django 6.0.7 on 2026-07-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_backfill_record_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvedregion',
            name='trigger',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
