# Generated by Django 6.0.7 on 2026-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_carvedregion_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='machine_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
