# Generated by Django 6.0.7 on 2026-07-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_host_machine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tier', models.CharField(blank=True, max_length=32)),
                ('reported_at', models.DateTimeField(db_index=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['tier', 'component'],
            },
        ),
    ]
