# Generated by Django 6.0.7 on 2026-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_lifecycle_and_sightings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(db_index=True, max_length=128)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('fmt', models.CharField(blank=True, max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('completed', 'completed'), ('denied', 'denied')], db_index=True, default='completed', max_length=16)),
                ('denied_reason', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['actor', '-id'], name='cases_expor_actor_da637e_idx'), models.Index(fields=['kind', '-id'], name='cases_expor_kind_541a88_idx'), models.Index(fields=['outcome', '-id'], name='cases_expor_outcome_7a9a6d_idx')],
            },
        ),
    ]
