# Generated by Django 6.0.7 on 2026-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_exportledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='sig_key_id',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='custodyevent',
            name='sig_key_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
