# Generated by Django 6.0.7 on 2026-08-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auditlog_sig_key_id_custodyevent_sig_key_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at_entry_id', models.BigIntegerField(db_index=True, unique=True)),
                ('observed_prev_hash', models.CharField(blank=True, max_length=64)),
                ('declared_prev_hash', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField()),
                ('recorded_by', models.CharField(max_length=128)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('sig_key_id', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['at_entry_id'],
            },
        ),
    ]
