# Generated by Django 6.0.7 on 2026-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_ssosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('queued', models.IntegerField(default=0)),
                ('running', models.IntegerField(default=0)),
                ('awaiting', models.IntegerField(default=0)),
                ('oldest_waiting_seconds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sampled_at'],
            },
        ),
    ]
