# Generated by Django 6.0.7 on 2026-08-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_queuesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_key', models.CharField(max_length=512)),
                ('bundle_sha256', models.CharField(max_length=64)),
                ('schema_version', models.CharField(blank=True, max_length=128)),
                ('row_counts', models.JSONField(blank=True, default=dict)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('archived_while_open', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('archived', 'archived'), ('restored', 'restored')], db_index=True, default='archived', max_length=16)),
                ('restored_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='cases.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('noop', 'noop')], db_index=True, default='pending', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restores', to='cases.investigationarchive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
