# Generated by Django 6.0.7 on 2026-08-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_investigationarchive_restorerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='compartment',
            field=models.CharField(choices=[('open', 'open'), ('restricted', 'restricted')], db_index=True, default='open', max_length=16),
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('assigned_by', models.CharField(blank=True, max_length=150)),
                ('removed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cases.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('investigation', 'username'), name='uniq_active_case_assignment')],
            },
        ),
    ]
