# Generated by Django 6.0.7 on 2026-08-12 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_investigation_compartment_caseassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('retired', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('imaging', 'imaging'), ('analysis', 'analysis'), ('peer_review', 'peer_review'), ('reported', 'reported')], db_index=True, default='imaging', max_length=16)),
                ('assignee', models.CharField(blank=True, db_index=True, max_length=150)),
                ('artifact_type', models.CharField(blank=True, max_length=32)),
                ('artifact_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.investigation')),
            ],
            options={
                'ordering': ['state', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.CharField(blank=True, max_length=150)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='cases.investigation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cases.casetag')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('investigation', 'tag'), name='uniq_case_tag')],
            },
        ),
    ]
