# Generated by Django 6.0.7 on 2026-08-12 22:09

import django.db.models.deletion
from django.db import migrations, models

# The board moved from four ad hoc columns to the digital forensics process.
STATE_MAP = {"imaging": "identification", "peer_review": "documentation",
             "reported": "presentation"}


def to_lifecycle(apps, schema_editor):
    task = apps.get_model("cases", "CaseTask")
    for old, new in STATE_MAP.items():
        task.objects.filter(state=old).update(state=new)


def to_previous(apps, schema_editor):
    task = apps.get_model("cases", "CaseTask")
    for old, new in STATE_MAP.items():
        task.objects.filter(state=new).update(state=old)
    task.objects.filter(state="preservation").update(state="analysis")


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_casetag_casetask_casetagassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='casetask',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='casetask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='state',
            field=models.CharField(choices=[('identification', 'Identification'), ('preservation', 'Preservation'), ('analysis', 'Analysis'), ('documentation', 'Documentation'), ('presentation', 'Presentation')], db_index=True, default='identification', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('document', 'document'), ('evidence', 'evidence')], db_index=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('added_by', models.CharField(blank=True, max_length=150)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('ref_type', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.casetask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.casetask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(to_lifecycle, to_previous),
    ]
