# Generated by Django 6.0.7 on 2026-08-12 22:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_casetask_blocked_casetask_blocked_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('summary', 'summary'), ('technical', 'technical')], db_index=True, max_length=16)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('sections', models.JSONField(default=list)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='kind',
            field=models.CharField(choices=[('observation', 'Observation'), ('analysis', 'Analysis'), ('decision', 'Decision'), ('action', 'Action taken'), ('containment', 'Containment'), ('eradication', 'Eradication'), ('handoff', 'Handoff'), ('request', 'Request'), ('summary', 'Case summary'), ('recommendation', 'Recommendation')], db_index=True, default='observation', max_length=16),
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.CharField(blank=True, max_length=32)),
                ('generated_by', models.CharField(blank=True, max_length=150)),
                ('data_as_of', models.DateTimeField()),
                ('fmt', models.CharField(default='md', max_length=8)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.investigation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renders', to='cases.reporttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuledOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hypothesis', models.CharField(max_length=255)),
                ('method', models.TextField(help_text='how it was tested')),
                ('rationale', models.TextField(blank=True)),
                ('tested_by', models.CharField(blank=True, max_length=150)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('concluded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruled_out', to='cases.investigation')),
            ],
            options={
                'ordering': ['-concluded_at'],
            },
        ),
    ]
