# Generated by Django 6.0.7 on 2026-08-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_reporttemplate_alter_note_kind_generatedreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='cases.investigation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_type', models.CharField(db_index=True, max_length=32)),
                ('ref_id', models.IntegerField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='cases.investigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ref_type', 'ref_id'), name='uniq_artifact_lock')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('mention', 'mention'), ('assignment', 'assignment'), ('handover', 'handover')], db_index=True, max_length=16)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('ref_type', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.investigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='cases_notif_user_id_e14563_idx')],
            },
        ),
    ]
