# Generated by Django 6.0.7 on 2026-08-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_presence_artifactlock_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReWorkset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('created_by', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('assembled', 'assembled'), ('staged', 'staged'), ('closed', 'closed')], db_index=True, default='assembled', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('staged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_worksets', to='cases.host')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_worksets', to='cases.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReWorksetRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField(default=0)),
                ('added_by', models.CharField(blank=True, max_length=128)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksets', to='cases.carvedregion')),
                ('workset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cases.reworkset')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reworkset',
            index=models.Index(fields=['investigation', 'state'], name='cases_rewor_investi_74a503_idx'),
        ),
        migrations.AddConstraint(
            model_name='reworksetregion',
            constraint=models.UniqueConstraint(fields=('workset', 'region'), name='uniq_region_per_workset'),
        ),
    ]
