# Generated by Django 6.0.7 on 2026-08-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_reworkset_reworksetregion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionanalysis',
            name='workset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determinations', to='cases.reworkset'),
        ),
    ]
