#!/usr/bin/env python3
"""Generate the worker-replica compose overlay for IR_WORKER_REPLICAS workers.

Stamped pairs are the tree's shape for replicas (the Boundary egress workers set it), but a
surge deployment is 20-50 workers — a SIEM flags forty hosts, memory is collected from all
of them at once — and nobody maintains forty hand-written YAML blocks. So the pairs are
GENERATED, deterministically, from the replica count; the checked-in overlay is the output
for the current setting and `deploy.sh` regenerates it whenever the count changes.

Addresses stay configuration, not discovery: the overlay references ${IR_IP_WORKERn} and
this script verifies deploy/.env declares every one it needs, printing the exact lines to
add when it does not. Replica n conventionally sits at 10.89.1.(211+n), giving .213-.250 —
a ceiling of 39 workers on the single-host bridge. Past that the answer is not more IPs, it
is analysis HOSTS (Track W5 / Nomad), where each host carries its own address.

    gen-worker-overlay.py <replicas> [--env deploy/.env] [--out <file>]
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
# The platform's supported worker-fleet cap for this phase. 5 proves the logic locally, 50
# is the walk target (an enterprise surge: a SIEM flags dozens of hosts, memory comes in
# from all of them); unlimited is the run phase, where Nomad provisions analysis hosts from
# available resources and this generator is superseded by a jobspec count.
MAX_WORKERS = 50
# How many replicas fit the single-host bridge: replica n sits at 10.89.1.(211+n), and
# .254 is the last usable address. Past this, more workers means analysis HOSTS (Track W5),
# not more bridge addresses.
MAX_LOCAL = 43

HEAD = '''\
# GENERATED by deploy/gen-worker-overlay.py — edit the generator, not this file.
# Worker replicas: identical consumers of the one analysis queue. Loaded by deploy.sh only
# when IR_WORKER_REPLICAS > 1. Each replica has its OWN scratch volume (shared scratch lets
# one replica's staging evict another's mid-analysis) and its own health and log identity.
# All replicas share the ir-worker ACL token: service-identity tokens are scoped to the
# service NAME, and every replica registers under ir-worker with a distinct ID, so the
# existing intentions cover all of them with no policy change.
version: "3"
services:
'''

PAIR = '''\
  worker-{n}:
    dns: ["${{ENCLAVE_DNS_IP}}"]
    dns_search: ["${{RUNTIME_DNS_ZONE}}"]
    image: localhost/ir-worker:latest
    command: ["worker"]
    env_file: ../.env
    environment:
      IR_LOG_NAME: worker-{n}
      IR_HEALTH_REPORT_ROLE: worker-{n}
      POSTGRES_HOST: ${{IR_DB_HOST_APP:-db}}
      S3_ENDPOINT_URL: ${{IR_MINIO_ENDPOINT_APP:-http://minio:9000}}
      IR_TOOLKIT_DIR: /opt/toolkit
      IR_SYMBOLS_DIR: /symbols
      VOLATILITY_SYMBOL_PATH: /symbols
      IR_VOL3_TIMEOUT: "10800"
      TMPDIR: /scratch
      IR_VAULT: "${{IR_VAULT:-1}}"
      # One analysis per replica: an OOM or runaway pass kills one analysis, not two, and
      # per-replica resource limits stay meaningful.
      CELERY_CONCURRENCY: "1"
    depends_on: [backend, redis, vault-agent]
    networks:
      internal:
        ipv4_address: ${{IR_IP_WORKER{n}}}
    volumes:
      - app-logs:/logs/app
      - vault-secrets:/vault/secrets:ro
      - symbols:/symbols:ro
      - worker-{n}-scratch:/scratch
    read_only: true
    cap_drop: [ALL]
    security_opt: ["no-new-privileges:true"]
    tmpfs: ["/tmp", "/run", "/home/worker/.cache"]

  worker-{n}-sidecar:
    mem_limit: ${{IR_SIDECAR_MEM:-128m}}
    image: localhost/ir-consul-sidecar:latest
    network_mode: "service:worker-{n}"
    depends_on: [worker-{n}]
    command: ["consul", "connect", "envoy", "-sidecar-for", "ir-worker-{n}",
              "-http-addr", "https://consul:8501", "-grpc-addr", "https://consul:8503",
              "-ca-file", "/consul/tls/consul-ca.pem", "-token-file", "/consul/tls/token",
              "-admin-bind", "127.0.0.1:19000",
              "--", "--concurrency", "${{IR_ENVOY_CONCURRENCY:-1}}"]
    volumes:
      - ../../hashicorp/consul/secrets/consul-ca.pem:/consul/tls/consul-ca.pem:ro,z
      - ../../hashicorp/consul/secrets/tokens/ir-worker.token:/consul/tls/token:ro,z
    restart: on-failure

'''


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a.split("=", 1) if "=" in a else (a, "") for a in sys.argv[1:] if a.startswith("--"))
    replicas = int(args[0]) if args else 1
    env_path = Path(opts.get("--env") or HERE / ".env")
    out_path = Path(opts.get("--out") or HERE / "enclave" / "docker-compose.workers.yml")

    if replicas + 1 > MAX_WORKERS:
        sys.exit(f"IR_WORKER_REPLICAS={replicas} exceeds the {MAX_WORKERS}-worker platform "
                 f"cap for this phase. Raising it is a capacity decision (connections, "
                 f"scratch, symbols distribution), not an edit here.")
    if replicas > MAX_LOCAL:
        sys.exit(f"IR_WORKER_REPLICAS={replicas} exceeds the single-host address ceiling "
                 f"({MAX_LOCAL}). More workers means analysis hosts (Track W5), not more "
                 f"bridge addresses.")

    env = env_path.read_text() if env_path.exists() else ""
    missing = []
    for n in range(2, replicas + 1):
        if not re.search(rf"^IR_IP_WORKER{n}=", env, re.M):
            missing.append(f"IR_IP_WORKER{n}=10.89.1.{211 + n}")
    if missing:
        sys.exit("deploy/.env is missing replica addresses — add:\n  " + "\n  ".join(missing))

    if replicas < 2:
        # No replicas declared: the overlay must not exist, or a stale one from a larger
        # setting would bring back workers the operator turned off.
        if out_path.exists():
            out_path.unlink()
            print(f"removed {out_path.name} (no replicas declared)")
        return

    body = (HEAD
            + "".join(PAIR.format(n=n) for n in range(2, replicas + 1))
            + "volumes:\n"
            + "".join(f"  worker-{n}-scratch:\n" for n in range(2, replicas + 1)))
    if out_path.exists() and out_path.read_text() == body:
        print(f"{out_path.name} current ({replicas - 1} replica pair(s))")
        return
    out_path.write_text(body)
    print(f"wrote {out_path.name}: worker-2..worker-{replicas} (+ sidecars, scratch volumes)")


if __name__ == "__main__":
    main()
