# Generated by Django 6.0.7 on 2026-08-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opslog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='opslog_requ_at_04faf7_idx',
            old_name='opslog_at_status_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='opslog_requ_usernam_e111c9_idx',
            old_name='opslog_user_at_idx',
        ),
    ]
